<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "publicrelations"
 *
 * Auto generated by Extension Builder 2020-08-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Public Relations',
    'description' => 'Extension for Public Relations Agencies.',
    'category' => 'plugin',
    'author' => 'Matthias Buchegger',
    'author_email' => 'matthias@buchegger.online',
    'state' => 'stable',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '13.4.8',
    'constraints' => [
        'depends' => [
            'typo3' => '13.4.0-13.9.99',
            'vhs' => '7.0.1-7.9.99',
            'static_info_tables' => '13.4.0-13.5.99',
            'tt_address' => '9.0.0-9.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => [
        'psr-4' => [
            'BucheggerOnline\\Publicrelations\\' => 'Classes/'
        ]
    ],
];
